# Generated by Django 2.1.5 on 2019-02-01 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Campaign', max_length=265)),
                ('organization', models.CharField(blank=True, max_length=265)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('crutch', 'crutch'), ('walker', 'walker'), ('wheelchair', 'wheelchair'), ('medical boot', 'medical boot'), ('orthotic shoe', 'orthotic shoe'), ('sling', 'sling'), ('glasses', 'glasses'), ('compression brace', 'compression brace'), ('orthotic brace', 'orthotic brace'), ('splint', 'splint'), ('wrap', 'wrap'), ('bed', 'bed')], max_length=25)),
                ('condition', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('BROKEN', 'Broken')], max_length=10)),
                ('donated_to_recipient', models.BooleanField(default='True')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_campaign', to='device_app.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='DonationHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265)),
                ('street', models.CharField(max_length=265)),
                ('city', models.CharField(max_length=265)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=265)),
                ('email', models.EmailField(max_length=265)),
                ('donation_house', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='dono_house', to='device_app.DonationHouse')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=265)),
                ('age', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(blank=True, choices=[('MAN', 'man'), ('WOMAN', 'woman'), ('BOY', 'boy'), ('GIRL', 'girl'), ('Non-Binary', 'non_binary')], max_length=13)),
                ('date_recieved', models.DateField(blank=True)),
                ('campaign', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='device_app.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='StorageArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265)),
                ('street', models.CharField(max_length=265)),
                ('city', models.CharField(max_length=265)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='device_app.Donor'),
        ),
        migrations.AddField(
            model_name='device',
            name='storage_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_storage_area', to='device_app.StorageArea'),
        ),
    ]
