# Generated by Django 2.1.5 on 2019-02-01 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
