# Generated by Django 2.1.5 on 2019-02-01 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0002_donor_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='date_donated_to_recipient',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
    ]
