# Generated by Django 2.1.5 on 2019-02-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0003_device_date_donated_to_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='donated_to_recipient',
            field=models.BooleanField(default='False'),
        ),
    ]
