# Generated by Django 2.1.5 on 2019-02-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0004_auto_20190201_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='donated_to_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
