# Generated by Django 2.1.5 on 2019-02-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0006_auto_20190201_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_donated_to_recipient',
            field=models.DateField(blank=True, null=True, verbose_name='Date Donated to Recipient (YYYY-MM-DD)'),
        ),
    ]
