# Generated by Django 2.1.5 on 2019-02-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0007_auto_20190201_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='organization',
            new_name='organization_recipient',
        ),
        migrations.AddField(
            model_name='campaign',
            name='Partnership',
            field=models.CharField(blank=True, max_length=265),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('crutch', 'crutch'), ('ez-crutch', 'EZ-crutch'), ('walker', 'walker'), ('wheelchair', 'wheelchair'), ('medical boot', 'medical boot'), ('orthotic shoe', 'orthotic shoe'), ('sling', 'sling'), ('glasses', 'glasses'), ('compression brace', 'compression brace'), ('orthotic brace', 'orthotic brace'), ('splint', 'splint'), ('wrap', 'wrap'), ('bed', 'bed'), ('miscellaneous', 'miscellaneous')], max_length=25),
        ),
    ]
