# Generated by Django 2.1.5 on 2019-02-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0008_auto_20190202_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='Partnership',
            new_name='partnership',
        ),
    ]
