# Generated by Django 2.1.5 on 2019-02-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0009_auto_20190202_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='organization_recipient',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='partnership',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
