# Generated by Django 2.1.5 on 2019-02-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0010_auto_20190202_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
