# Generated by Django 2.1.5 on 2019-02-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0011_device_cleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unique_information',
            field=models.TextField(default=False, max_length=265),
        ),
    ]
