# Generated by Django 2.1.5 on 2019-02-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0012_device_unique_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unique_information',
            field=models.CharField(max_length=100),
        ),
    ]
