# Generated by Django 2.1.5 on 2019-02-23 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0014_auto_20190223_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='date_donated_to_project_embrace',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
