# Generated by Django 2.1.5 on 2019-02-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0015_device_date_donated_to_project_embrace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='cleaned',
            new_name='processed',
        ),
    ]
