# Generated by Django 2.1.5 on 2019-02-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0016_auto_20190223_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unique_information',
            field=models.TextField(default='None'),
        ),
    ]
