# Generated by Django 2.2.4 on 2019-09-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0018_auto_20190811_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('cane', 'cane'), ('quad cane', 'quad cane'), ('adult crutch', 'adult crutch'), ('adult forearm crutch', 'adult forearm crutch'), ('pediatric crutch', 'pediatric crutch'), ('pediatric forearm crutch', 'pediatric forarm crutch'), ('EZ_crutch', 'EZ-crutch'), ('nonwheeled walker', 'nonwheeled walker'), ('two wheeled walker', 'two wheeled walker'), ('three wheeled walker', 'three wheeled walker'), ('four wheeled walker', 'four wheeled walker'), ('knee injury scooter', 'knee injury scooter'), ('standard wheelchair', 'standard wheelchair'), ('active manual wheelchair', 'active manual wheelchair'), ('pediatric wheelchair', 'pediatric wheelchair'), ('adult medical boot', 'adult medical boot'), ('pediatric medical boot', 'pediatric medical boot'), ('orthotic brace', 'orthotic brace'), ('orthotic shoe', 'orthotic shoe'), ('compression brace', 'compression brace'), ('sling', 'sling'), ('showerchair', 'shower chair'), ('commode', 'commode'), ('glasses', 'glasses'), ('splint', 'splint'), ('wrap', 'wrap'), ('bed', 'bed'), ('miscellaneous', 'miscellaneous')], max_length=25),
        ),
    ]
