# Generated by Django 2.2.4 on 2019-09-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0021_auto_20190930_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentvalue',
            name='source_value',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
