# Generated by Django 2.2.4 on 2019-10-02 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0022_equipmentvalue_source_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='storage_unit',
            field=models.IntegerField(default=109, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='storage_unit_quadrant',
            field=models.CharField(default=104, max_length=6),
            preserve_default=False,
        ),
    ]
