# Generated by Django 2.2.4 on 2019-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0023_auto_20191002_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='sent_a_receipt',
            field=models.BooleanField(default=False),
        ),
    ]
