# Generated by Django 2.2.4 on 2019-11-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0024_donor_sent_a_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ('donation_date',)},
        ),
        migrations.AlterField(
            model_name='equipmentvalue',
            name='device_type',
            field=models.CharField(choices=[('cane', 'cane'), ('quad cane', 'cane: quad'), ('crutch_adult', 'crutch: adult'), ('crutch_pediatric', 'crutch: pediatric'), ('forearm_crutch_adult', 'forearm crutch: adult'), ('forearm_crutch_pediatric', 'forearm crutch: pediatric'), ('walker_nonwheeled', 'walker: non-wheeled'), ('walker_two_wheeled', 'walker: two-wheeled'), ('walker_three_wheeled', 'walker: three-wheeled'), ('walker_four_wheeled', 'walker: four-wheeled'), ('knee injury scooter', 'knee injury scooter'), ('wheelchair_standard', 'wheelchair: standard'), ('wheelchair_active_manual', 'wheelchair: active-manual'), ('wheelchair_pediatric', 'wheelchair: pediatric'), ('medical_boot_adult', 'medical boot: adult'), ('medical_boot_pediatric', 'medical boot: pediatric'), ('orthotic_brace_adult', 'orthotic brace: adult'), ('orthotic_brace_pediatric', 'orthotic brace: pediatric'), ('orthotic_shoe_adult', 'orthotic shoe: adult'), ('orthotic_shoe_pediatric', 'orthotic shoe: pediatric'), ('compression brace', 'compression brace'), ('sling', 'sling'), ('showerchair', 'shower chair'), ('btshowerchair', 'tub attachable shower chair'), ('commode', 'commode'), ('glasses', 'glasses'), ('splint', 'splint'), ('splint', 'wrist splint'), ('miscellaneous', 'miscellaneous')], max_length=25),
        ),
    ]
