# Generated by Django 2.2.4 on 2019-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0025_auto_20191101_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('btshowerchair', 'tub attachable shower chair'), ('cane', 'cane'), ('commode', 'commode'), ('compression brace', 'compression brace'), ('crutch_adult', 'crutch: adult'), ('crutch_pediatric', 'crutch: pediatric'), ('forearm_crutch_adult', 'forearm crutch: adult'), ('forearm_crutch_pediatric', 'forearm crutch: pediatric'), ('glasses', 'glasses'), ('knee injury scooter', 'knee injury scooter'), ('medical_boot_adult', 'medical boot: adult'), ('medical_boot_pediatric', 'medical boot: pediatric'), ('miscellaneous', 'miscellaneous'), ('orthotic_brace_adult', 'orthotic brace: adult'), ('orthotic_brace_pediatric', 'orthotic brace: pediatric'), ('orthotic_shoe_adult', 'orthotic shoe: adult'), ('orthotic_shoe_pediatric', 'orthotic shoe: pediatric'), ('quad cane', 'cane: quad'), ('showerchair', 'shower chair'), ('sling', 'sling'), ('splint', 'splint'), ('splint', 'wrist splint'), ('walker_four_wheeled', 'walker: four-wheeled'), ('walker_nonwheeled', 'walker: non-wheeled'), ('walker_three_wheeled', 'walker: three-wheeled'), ('walker_two_wheeled', 'walker: two-wheeled'), ('wheelchair_active_manual', 'wheelchair: active-manual'), ('wheelchair_pediatric', 'wheelchair: pediatric'), ('wheelchair_standard', 'wheelchair: standard')], max_length=25),
        ),
        migrations.AlterField(
            model_name='equipmentvalue',
            name='device_type',
            field=models.CharField(choices=[('btshowerchair', 'tub attachable shower chair'), ('cane', 'cane'), ('commode', 'commode'), ('compression brace', 'compression brace'), ('crutch_adult', 'crutch: adult'), ('crutch_pediatric', 'crutch: pediatric'), ('forearm_crutch_adult', 'forearm crutch: adult'), ('forearm_crutch_pediatric', 'forearm crutch: pediatric'), ('glasses', 'glasses'), ('knee injury scooter', 'knee injury scooter'), ('medical_boot_adult', 'medical boot: adult'), ('medical_boot_pediatric', 'medical boot: pediatric'), ('miscellaneous', 'miscellaneous'), ('orthotic_brace_adult', 'orthotic brace: adult'), ('orthotic_brace_pediatric', 'orthotic brace: pediatric'), ('orthotic_shoe_adult', 'orthotic shoe: adult'), ('orthotic_shoe_pediatric', 'orthotic shoe: pediatric'), ('quad cane', 'cane: quad'), ('showerchair', 'shower chair'), ('sling', 'sling'), ('splint', 'splint'), ('splint', 'wrist splint'), ('walker_four_wheeled', 'walker: four-wheeled'), ('walker_nonwheeled', 'walker: non-wheeled'), ('walker_three_wheeled', 'walker: three-wheeled'), ('walker_two_wheeled', 'walker: two-wheeled'), ('wheelchair_active_manual', 'wheelchair: active-manual'), ('wheelchair_pediatric', 'wheelchair: pediatric'), ('wheelchair_standard', 'wheelchair: standard')], max_length=25),
        ),
    ]
