# Generated by Django 2.2.4 on 2019-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_app', '0032_auto_20191104_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='country',
            field=models.CharField(default='Not Disclosed', max_length=265),
        ),
        migrations.AddField(
            model_name='campaign',
            name='region',
            field=models.CharField(default='Not Disclosed', max_length=265),
        ),
        migrations.AddField(
            model_name='donor',
            name='country',
            field=models.CharField(default='Not Disclosed', max_length=265),
        ),
        migrations.AddField(
            model_name='donor',
            name='region',
            field=models.CharField(default='Not Disclosed', max_length=265),
        ),
    ]
