# Generated by Django 2.2.4 on 2019-11-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_findocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentvalue',
            name='source_value',
            field=models.IntegerField(),
        ),
    ]
