# Generated by Django 2.2.4 on 2019-11-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20191118_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentvalue',
            name='source_value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
