# Generated by Django 2.2.8 on 2019-12-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20191209_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='storage_unit',
            field=models.CharField(choices=[('109', '109'), ('115', '115'), ('Donated Item', 'Donated Item')], max_length=3),
        ),
        migrations.AlterField(
            model_name='device',
            name='storage_unit_quadrant',
            field=models.CharField(choices=[('Donated Item', 'Donated Item'), ('Q1', 'Q1`'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=6),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('cane', 'cane'), ('cane, quad', 'cane, quad'), ('commode', 'commode'), ('compression brace', 'compression brace'), ('crutch, adult', 'crutch, adult'), ('crutch, pediatric', 'crutch, pediatric'), ('forearm crutch, adult', 'forearm crutch, adult'), ('forearm crutch, pediatric', 'forearm crutch, pediatric'), ('knee injury scooter', 'knee injury scooter'), ('medical boot, adult', 'medical boot adult'), ('medical boot, pediatric', 'medical boot, pediatric'), ('miscellaneous', 'miscellaneous'), ('orthotic brace, adult', 'orthotic brace adult'), ('orthotic brace, pediatric', 'orthotic brace, pediatric'), ('orthotic shoe, adult', 'orthotic shoe, adult'), ('orthotic shoe, pediatric', 'orthotic shoe, pediatric'), ('shower chair, tub-attachable', 'shower chair, tub-attachable'), ('showerchair', 'shower chair'), ('sling', 'sling'), ('splint', 'splint'), ('splint, wrist', 'wrist, splint'), ('walker, four-wheeled', 'walker, four-wheeled'), ('walker, non-wheeled', 'walker, non-wheeled'), ('walker, three-wheeled', 'walker, three-wheeled'), ('walker, two-wheeled', 'walker, two-wheeled'), ('wheelchair, active-manual', 'wheelchair, active-manual'), ('wheelchair, pediatric', 'wheelchair, pediatric'), ('wheelchair, seat cushion', 'wheelchair, seat cushion'), ('wheelchair, standard', 'wheelchair, standard')], max_length=47),
        ),
    ]
