# Generated by Django 2.2.8 on 2019-12-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20191209_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='storage_unit_quadrant',
            field=models.CharField(choices=[('Donated Item', 'Donated Item'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=13),
        ),
    ]
